import type { Booking, ProviderProfile, Review, ServiceCategory, User } from '@/types'

const now = Date.now()
const daysAgo = (d: number) => new Date(now - d * 86400000).toISOString()
const daysAhead = (d: number) => new Date(now + d * 86400000).toISOString()

export const seedCategories: ServiceCategory[] = [
  {
    id: 'cat-electrician',
    name: 'Electrician',
    slug: 'electrician',
    description: 'Wiring, switchboards, fixture installation and electrical repairs',
    icon: 'zap',
    basePrice: 299,
    active: true,
    longDescription: 'From fixing a faulty switchboard to complete house rewiring, our certified electricians handle all residential and commercial electrical work with safety as the top priority. Same-day service available for most repairs.',
    includes: ['Switchboard repair and replacement', 'MCB / RCCB installation', 'Fan and light fixture installation', 'Wiring and rewiring', 'Power backup and inverter setup', 'Earth leakage testing'],
    estimatedDuration: '1–3 hours',
    whyUs: ['Licensed and insured professionals', 'Safety-certified equipment', 'Warranty on all work', 'Transparent pricing — no hidden charges'],
    tips: 'Turn off the mains before we arrive. List all the issues you need fixed so we can quote accurately.',
  },
  {
    id: 'cat-plumber',
    name: 'Plumber',
    slug: 'plumber',
    description: 'Leak repair, tap and pipe fitting, bathroom installations',
    icon: 'wrench',
    basePrice: 249,
    active: true,
    longDescription: 'Leaky taps, clogged drains, bathroom installations — our plumbers fix it all. Fully equipped for both minor repairs and major renovation work across Pune.',
    includes: ['Tap and mixer repair / replacement', 'Pipe leak detection and fixing', 'Basin, sink and geyser installation', 'Drain and sewer unclogging', 'Bathroom waterproofing', 'Concealed piping'],
    estimatedDuration: '1–4 hours',
    whyUs: ['10+ years experience on average', 'Latest diagnostic tools', 'Guaranteed workmanship', 'Emergency service available'],
    tips: 'Clear the area under the sink or around the fixture. Take photos of the issue if possible.',
  },
  {
    id: 'cat-ac-repair',
    name: 'AC Repair',
    slug: 'ac-repair',
    description: 'AC servicing, gas refill, installation and uninstallation',
    icon: 'wind',
    basePrice: 499,
    active: true,
    longDescription: 'Beat the Pune heat! Expert AC servicing, repair and installation for all brands — split, window, cassette and central systems. We use eco-friendly refrigerants and follow all safety protocols.',
    includes: ['Split AC servicing and gas refill', 'Window AC installation and removal', 'PCB and compressor repair', 'Coil cleaning and deep service', 'Inverter AC diagnostics', 'AMC contracts for homes and offices'],
    estimatedDuration: '1–3 hours',
    whyUs: ['Certified HVAC technicians', 'All major brands covered', 'Genuine spare parts', 'Service warranty provided'],
    tips: 'Clean or replace your AC filters monthly. Schedule servicing before summer for best rates.',
  },
  {
    id: 'cat-cleaning',
    name: 'Home Cleaning',
    slug: 'home-cleaning',
    description: 'Deep cleaning for kitchens, bathrooms and full homes',
    icon: 'sparkles',
    basePrice: 799,
    active: true,
    longDescription: 'Deep cleaning that actually makes a difference. Our trained teams use eco-friendly products and professional-grade equipment to transform your home from top to bottom.',
    includes: ['Full home deep clean (1BHK / 2BHK / 3BHK)', 'Kitchen: chimney, hob, cabinets, tiles', 'Bathroom: scrubbing, descaling, disinfection', 'Sofa and carpet shampooing', 'Marble and tile polishing', 'Balcony and window cleaning'],
    estimatedDuration: '3–8 hours (depends on home size)',
    whyUs: ['Trained and background-checked staff', 'Eco-friendly, pet-safe chemicals', 'Equipment brought by the team', 'Satisfaction guaranteed or we re-clean free'],
    tips: 'Secure valuables and small items. Let us know about any delicate surfaces beforehand.',
  },
  {
    id: 'cat-salon',
    name: 'Salon at Home',
    slug: 'salon-at-home',
    description: 'Haircuts, grooming, facials and beauty services at your door',
    icon: 'scissors',
    basePrice: 399,
    active: true,
    longDescription: 'Premium salon services at your doorstep. No more traffic and waiting — our experienced stylists and beauticians bring the full salon experience to your home.',
    includes: ['Haircut, styling and colouring', 'Facial and clean-up for all skin types', 'Bridal and party makeup', 'Manicure and pedicure', 'Threading, waxing and bleaching', 'Mehendi application'],
    estimatedDuration: '30 min – 3 hours',
    whyUs: ['Professional-grade products used', 'Hygiene-certified tools', 'Experienced with all hair and skin types', 'Flexible timings — early morning to late evening'],
    tips: 'Wash your hair before a haircut appointment. For facials, avoid makeup beforehand.',
  },
]

// Seeded accounts. Password for every seed account: "password"
export const seedUsers: User[] = [
  {
    id: 'user-customer-1',
    name: 'Aarav Kulkarni',
    email: 'customer@demo.com',
    phone: '+91 98220 11001',
    role: 'CUSTOMER',
    createdAt: daysAgo(90),
  },
  {
    id: 'user-admin-1',
    name: 'Admin',
    email: 'admin@demo.com',
    phone: '+91 98220 00001',
    role: 'ADMIN',
    createdAt: daysAgo(365),
  },
  // provider users (one per provider profile below)
  ...[
    ['user-prov-1', 'Ramesh Patil', 'ramesh@demo.com'],
    ['user-prov-2', 'Suresh Jadhav', 'suresh@demo.com'],
    ['user-prov-3', 'Vikram Shinde', 'provider@demo.com'],
    ['user-prov-4', 'Anil Deshmukh', 'anil@demo.com'],
    ['user-prov-5', 'Mahesh Gaikwad', 'mahesh@demo.com'],
    ['user-prov-6', 'Santosh More', 'santosh@demo.com'],
    ['user-prov-7', 'Prakash Bhosale', 'prakash@demo.com'],
    ['user-prov-8', 'Deepa Joshi', 'deepa@demo.com'],
    ['user-prov-9', 'Kavita Pawar', 'kavita@demo.com'],
    ['user-prov-10', 'Sunita Kadam', 'sunita@demo.com'],
    ['user-prov-11', 'Rahul Salunkhe', 'rahul@demo.com'],
    ['user-prov-12', 'Nilesh Chavan', 'nilesh@demo.com'],
  ].map(([id, name, email], i) => ({
    id,
    name,
    email,
    phone: `+91 98220 2${String(1000 + i).slice(1)}`,
    role: 'PROVIDER' as const,
    createdAt: daysAgo(200 - i * 10),
  })),
]

// Providers spread across Pune localities
export const seedProviders: ProviderProfile[] = [
  {
    id: 'prov-1',
    userId: 'user-prov-1',
    name: 'Ramesh Patil',
    categoryId: 'cat-electrician',
    bio: '15 years of residential wiring and switchboard work across Kothrud and Karve Nagar. Licensed and insured.',
    yearsExperience: 15,
    hourlyRate: 350,
    lat: 18.5074,
    lng: 73.8077,
    areaLabel: 'Kothrud',
    rating: 4.8,
    reviewCount: 132,
    available: true,
    verificationStatus: 'VERIFIED',
    completedJobs: 410,
  },
  {
    id: 'prov-2',
    userId: 'user-prov-2',
    name: 'Suresh Jadhav',
    categoryId: 'cat-electrician',
    bio: 'Specialist in inverter setups, MCB panels and fault finding. Same-day service in and around Hadapsar.',
    yearsExperience: 9,
    hourlyRate: 300,
    lat: 18.5089,
    lng: 73.926,
    areaLabel: 'Hadapsar',
    rating: 4.5,
    reviewCount: 78,
    available: true,
    verificationStatus: 'VERIFIED',
    completedJobs: 215,
  },
  {
    id: 'prov-3',
    userId: 'user-prov-3',
    name: 'Vikram Shinde',
    categoryId: 'cat-plumber',
    bio: 'Bathroom fittings, concealed piping and leak detection. Trusted by housing societies in Baner and Aundh.',
    yearsExperience: 12,
    hourlyRate: 320,
    lat: 18.5599,
    lng: 73.7897,
    areaLabel: 'Baner',
    rating: 4.7,
    reviewCount: 96,
    available: true,
    verificationStatus: 'VERIFIED',
    completedJobs: 305,
  },
  {
    id: 'prov-4',
    userId: 'user-prov-4',
    name: 'Anil Deshmukh',
    categoryId: 'cat-plumber',
    bio: 'Quick fixes to full bathroom renovations. Serving Viman Nagar, Kharadi and Wadgaon Sheri.',
    yearsExperience: 7,
    hourlyRate: 280,
    lat: 18.5679,
    lng: 73.9143,
    areaLabel: 'Viman Nagar',
    rating: 4.3,
    reviewCount: 54,
    available: false,
    verificationStatus: 'VERIFIED',
    completedJobs: 148,
  },
  {
    id: 'prov-5',
    userId: 'user-prov-5',
    name: 'Mahesh Gaikwad',
    categoryId: 'cat-ac-repair',
    bio: 'Certified HVAC technician. Split and window AC servicing, gas charging, PCB repair. All brands.',
    yearsExperience: 11,
    hourlyRate: 450,
    lat: 18.5308,
    lng: 73.8475,
    areaLabel: 'Shivajinagar',
    rating: 4.9,
    reviewCount: 201,
    available: true,
    verificationStatus: 'VERIFIED',
    completedJobs: 520,
  },
  {
    id: 'prov-6',
    userId: 'user-prov-6',
    name: 'Santosh More',
    categoryId: 'cat-ac-repair',
    bio: 'AC installation and AMC contracts for homes and small offices in Wakad and Hinjawadi.',
    yearsExperience: 6,
    hourlyRate: 400,
    lat: 18.5975,
    lng: 73.7629,
    areaLabel: 'Wakad',
    rating: 4.4,
    reviewCount: 63,
    available: true,
    verificationStatus: 'VERIFIED',
    completedJobs: 170,
  },
  {
    id: 'prov-7',
    userId: 'user-prov-7',
    name: 'Prakash Bhosale',
    categoryId: 'cat-cleaning',
    bio: 'Team of 4 for full-home deep cleaning, sofa shampooing and marble polishing. Eco-friendly chemicals.',
    yearsExperience: 8,
    hourlyRate: 500,
    lat: 18.4634,
    lng: 73.865,
    areaLabel: 'Katraj',
    rating: 4.6,
    reviewCount: 88,
    available: true,
    verificationStatus: 'VERIFIED',
    completedJobs: 260,
  },
  {
    id: 'prov-8',
    userId: 'user-prov-8',
    name: 'Deepa Joshi',
    categoryId: 'cat-cleaning',
    bio: 'Kitchen and bathroom deep-clean specialist. Serving Kalyani Nagar and Koregaon Park.',
    yearsExperience: 5,
    hourlyRate: 450,
    lat: 18.5481,
    lng: 73.9021,
    areaLabel: 'Kalyani Nagar',
    rating: 4.7,
    reviewCount: 71,
    available: true,
    verificationStatus: 'VERIFIED',
    completedJobs: 190,
  },
  {
    id: 'prov-9',
    userId: 'user-prov-9',
    name: 'Kavita Pawar',
    categoryId: 'cat-salon',
    bio: 'Bridal makeup, facials and haircuts at home. 10 years with premium salons before going independent.',
    yearsExperience: 10,
    hourlyRate: 600,
    lat: 18.5203,
    lng: 73.8567,
    areaLabel: 'Deccan',
    rating: 4.9,
    reviewCount: 154,
    available: true,
    verificationStatus: 'VERIFIED',
    completedJobs: 380,
  },
  {
    id: 'prov-10',
    userId: 'user-prov-10',
    name: 'Sunita Kadam',
    categoryId: 'cat-salon',
    bio: 'Threading, waxing, mehendi and party makeup. Serving Sinhagad Road and Dhayari.',
    yearsExperience: 4,
    hourlyRate: 400,
    lat: 18.4823,
    lng: 73.8199,
    areaLabel: 'Sinhagad Road',
    rating: 4.2,
    reviewCount: 39,
    available: true,
    verificationStatus: 'VERIFIED',
    completedJobs: 95,
  },
  // pending verification — visible only in admin queue
  {
    id: 'prov-11',
    userId: 'user-prov-11',
    name: 'Rahul Salunkhe',
    categoryId: 'cat-electrician',
    bio: 'New to the platform. 3 years experience with residential electrical work in Pimpri-Chinchwad.',
    yearsExperience: 3,
    hourlyRate: 250,
    lat: 18.6298,
    lng: 73.7997,
    areaLabel: 'Pimpri',
    rating: 0,
    reviewCount: 0,
    available: false,
    verificationStatus: 'PENDING',
    completedJobs: 0,
  },
  {
    id: 'prov-12',
    userId: 'user-prov-12',
    name: 'Nilesh Chavan',
    categoryId: 'cat-plumber',
    bio: 'Plumbing contractor moving to on-demand work. Based in Kondhwa.',
    yearsExperience: 6,
    hourlyRate: 300,
    lat: 18.4695,
    lng: 73.8931,
    areaLabel: 'Kondhwa',
    rating: 0,
    reviewCount: 0,
    available: false,
    verificationStatus: 'PENDING',
    completedJobs: 0,
  },
]

// One booking in every status so the whole UI is visible immediately
export const seedBookings: Booking[] = [
  {
    id: 'bk-1001',
    customerId: 'user-customer-1',
    customerName: 'Aarav Kulkarni',
    providerId: 'prov-1',
    providerName: 'Ramesh Patil',
    categoryId: 'cat-electrician',
    categoryName: 'Electrician',
    status: 'REQUESTED',
    scheduledAt: daysAhead(2),
    address: 'B-402, Gulmohar Residency, Kothrud, Pune 411038',
    notes: 'Two switchboards sparking in the living room. Please bring spare MCBs.',
    price: 350,
    paymentReceived: false,
    createdAt: daysAgo(0.2),
    updatedAt: daysAgo(0.2),
  },
  {
    id: 'bk-1002',
    customerId: 'user-customer-1',
    customerName: 'Aarav Kulkarni',
    providerId: 'prov-5',
    providerName: 'Mahesh Gaikwad',
    categoryId: 'cat-ac-repair',
    categoryName: 'AC Repair',
    status: 'ACCEPTED',
    scheduledAt: daysAhead(1),
    address: 'B-402, Gulmohar Residency, Kothrud, Pune 411038',
    notes: 'Split AC not cooling, likely needs a gas refill.',
    price: 450,
    paymentReceived: false,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(0.5),
  },
  {
    id: 'bk-1003',
    customerId: 'user-customer-1',
    customerName: 'Aarav Kulkarni',
    providerId: 'prov-3',
    providerName: 'Vikram Shinde',
    categoryId: 'cat-plumber',
    categoryName: 'Plumber',
    status: 'IN_PROGRESS',
    scheduledAt: daysAgo(0.1),
    address: 'B-402, Gulmohar Residency, Kothrud, Pune 411038',
    notes: 'Kitchen sink pipe leaking under the counter.',
    price: 320,
    paymentReceived: true,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(0.05),
  },
  {
    id: 'bk-1004',
    customerId: 'user-customer-1',
    customerName: 'Aarav Kulkarni',
    providerId: 'prov-7',
    providerName: 'Prakash Bhosale',
    categoryId: 'cat-cleaning',
    categoryName: 'Home Cleaning',
    status: 'COMPLETED',
    scheduledAt: daysAgo(3),
    address: 'B-402, Gulmohar Residency, Kothrud, Pune 411038',
    notes: 'Full 2BHK deep clean before Diwali.',
    price: 1500,
    paymentReceived: true,
    createdAt: daysAgo(5),
    updatedAt: daysAgo(3),
  },
  {
    id: 'bk-1005',
    customerId: 'user-customer-1',
    customerName: 'Aarav Kulkarni',
    providerId: 'prov-9',
    providerName: 'Kavita Pawar',
    categoryId: 'cat-salon',
    categoryName: 'Salon at Home',
    status: 'RATED',
    scheduledAt: daysAgo(10),
    address: 'B-402, Gulmohar Residency, Kothrud, Pune 411038',
    notes: 'Haircut and facial for two people.',
    price: 1200,
    paymentReceived: true,
    createdAt: daysAgo(12),
    updatedAt: daysAgo(9),
  },
  {
    id: 'bk-1006',
    customerId: 'user-customer-1',
    customerName: 'Aarav Kulkarni',
    providerId: 'prov-2',
    providerName: 'Suresh Jadhav',
    categoryId: 'cat-electrician',
    categoryName: 'Electrician',
    status: 'CANCELLED',
    scheduledAt: daysAgo(6),
    address: 'B-402, Gulmohar Residency, Kothrud, Pune 411038',
    notes: 'Fan installation in the bedroom.',
    price: 300,
    paymentReceived: false,
    createdAt: daysAgo(8),
    updatedAt: daysAgo(7),
  },
]

export const seedReviews: Review[] = [
  {
    id: 'rev-1',
    bookingId: 'bk-1005',
    providerId: 'prov-9',
    customerId: 'user-customer-1',
    customerName: 'Aarav Kulkarni',
    rating: 5,
    comment: 'Kavita was punctual and extremely professional. Best at-home salon experience so far.',
    createdAt: daysAgo(9),
  },
  {
    id: 'rev-2',
    bookingId: 'bk-old-1',
    providerId: 'prov-1',
    customerId: 'user-x1',
    customerName: 'Priya Nair',
    rating: 5,
    comment: 'Fixed a tricky wiring fault other electricians had given up on. Highly recommended.',
    createdAt: daysAgo(20),
  },
  {
    id: 'rev-3',
    bookingId: 'bk-old-2',
    providerId: 'prov-1',
    customerId: 'user-x2',
    customerName: 'Rohan Mehta',
    rating: 4,
    comment: 'Good work, arrived 20 minutes late but finished quickly.',
    createdAt: daysAgo(35),
  },
  {
    id: 'rev-4',
    bookingId: 'bk-old-3',
    providerId: 'prov-5',
    customerId: 'user-x3',
    customerName: 'Sneha Kulkarni',
    rating: 5,
    comment: 'AC works like new. Explained the issue clearly and charged fairly.',
    createdAt: daysAgo(15),
  },
  {
    id: 'rev-5',
    bookingId: 'bk-old-4',
    providerId: 'prov-3',
    customerId: 'user-x4',
    customerName: 'Amit Bhagwat',
    rating: 4,
    comment: 'Solid plumbing work, cleaned up after finishing.',
    createdAt: daysAgo(28),
  },
]
